// <auto-generated />
using System;
using Bus_system_prototype.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bus_system_prototype.Migrations
{
    [DbContext(typeof(context))]
    [Migration("20250307145745_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bus_system_prototype.Models.Bus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AirConditioning")
                        .HasColumnType("bit");

                    b.Property<bool>("Drinks")
                        .HasColumnType("bit");

                    b.Property<string>("ImgURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Snacks")
                        .HasColumnType("bit");

                    b.Property<bool>("TV")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("WiFi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Buses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AirConditioning = true,
                            Drinks = true,
                            ImgURL = "~/uploads/bus1.jpeg",
                            Snacks = true,
                            TV = true,
                            Type = "Luxury",
                            WiFi = true
                        },
                        new
                        {
                            Id = 2,
                            AirConditioning = true,
                            Drinks = false,
                            ImgURL = "~/uploads/bus2.jpeg",
                            Snacks = false,
                            TV = false,
                            Type = "Standard",
                            WiFi = false
                        },
                        new
                        {
                            Id = 3,
                            AirConditioning = true,
                            Drinks = true,
                            ImgURL = "~/uploads/bus3.jpeg",
                            Snacks = true,
                            TV = true,
                            Type = "Comfort",
                            WiFi = false
                        },
                        new
                        {
                            Id = 4,
                            AirConditioning = true,
                            Drinks = true,
                            ImgURL = "~/uploads/bus4.jpeg",
                            Snacks = false,
                            TV = true,
                            Type = "Premium",
                            WiFi = true
                        });
                });

            modelBuilder.Entity("Bus_system_prototype.Models.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImgURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImgURL = "~/uploads/Alex.jpeg",
                            Location = "Alexandria, Egypt",
                            Name = "Alexandria"
                        },
                        new
                        {
                            Id = 2,
                            ImgURL = "~/uploads/Dahab.jpeg",
                            Location = "Dahab, Egypt",
                            Name = "Dahab"
                        },
                        new
                        {
                            Id = 3,
                            ImgURL = "~/uploads/hurghada.jpeg",
                            Location = "Hurghada, Egypt",
                            Name = "Hurghada"
                        },
                        new
                        {
                            Id = 4,
                            ImgURL = "~/uploads/Marsa-Alam.jpeg",
                            Location = "Marsa Alam, Egypt",
                            Name = "Marsa Alam"
                        },
                        new
                        {
                            Id = 5,
                            ImgURL = "~/uploads/Nuweiba.jpeg",
                            Location = "Nuweiba, Egypt",
                            Name = "Nuweiba"
                        });
                });

            modelBuilder.Entity("Bus_system_prototype.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BusId")
                        .HasColumnType("int");

                    b.Property<int>("FromStationId")
                        .HasColumnType("int");

                    b.Property<int>("TOStationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TripDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BusId");

                    b.HasIndex("FromStationId");

                    b.HasIndex("TOStationId");

                    b.ToTable("Trips");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BusId = 1,
                            FromStationId = 1,
                            TOStationId = 3,
                            TripDate = new DateTime(2025, 3, 14, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            BusId = 2,
                            FromStationId = 3,
                            TOStationId = 5,
                            TripDate = new DateTime(2025, 3, 15, 12, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            BusId = 3,
                            FromStationId = 2,
                            TOStationId = 4,
                            TripDate = new DateTime(2025, 3, 16, 14, 45, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            BusId = 4,
                            FromStationId = 5,
                            TOStationId = 1,
                            TripDate = new DateTime(2025, 3, 17, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Bus_system_prototype.Models.Trip", b =>
                {
                    b.HasOne("Bus_system_prototype.Models.Bus", "Bus")
                        .WithMany()
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Bus_system_prototype.Models.Station", "FromStation")
                        .WithMany()
                        .HasForeignKey("FromStationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Bus_system_prototype.Models.Station", "TOStation")
                        .WithMany()
                        .HasForeignKey("TOStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bus");

                    b.Navigation("FromStation");

                    b.Navigation("TOStation");
                });
#pragma warning restore 612, 618
        }
    }
}
