// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Transport_system_prototype.Models;

#nullable disable

namespace Transport__system_prototype.Migrations
{
    [DbContext(typeof(context))]
    partial class contextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Transport_system_prototype.Models.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImgURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImgURL = "~/uploads/Alex.jpeg",
                            Location = "Alexandria, Egypt",
                            Name = "Alexandria"
                        },
                        new
                        {
                            Id = 2,
                            ImgURL = "~/uploads/Dahab.jpeg",
                            Location = "Dahab, Egypt",
                            Name = "Dahab"
                        },
                        new
                        {
                            Id = 3,
                            ImgURL = "~/uploads/hurghada.jpeg",
                            Location = "Hurghada, Egypt",
                            Name = "Hurghada"
                        },
                        new
                        {
                            Id = 4,
                            ImgURL = "~/uploads/Marsa-Alam.jpeg",
                            Location = "Marsa Alam, Egypt",
                            Name = "Marsa Alam"
                        },
                        new
                        {
                            Id = 5,
                            ImgURL = "~/uploads/Nuweiba.jpeg",
                            Location = "Nuweiba, Egypt",
                            Name = "Nuweiba"
                        });
                });

            modelBuilder.Entity("Transport_system_prototype.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<int>("FromStationId")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfSeats")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("TOStationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TripDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("vehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FromStationId");

                    b.HasIndex("TOStationId");

                    b.HasIndex("vehicleId");

                    b.ToTable("Trips");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableSeats = 10,
                            FromStationId = 1,
                            NumberOfSeats = 10,
                            Price = 300,
                            TOStationId = 3,
                            TripDate = new DateTime(2025, 3, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            vehicleId = 1
                        },
                        new
                        {
                            Id = 2,
                            AvailableSeats = 50,
                            FromStationId = 3,
                            NumberOfSeats = 50,
                            Price = 300,
                            TOStationId = 5,
                            TripDate = new DateTime(2025, 3, 15, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            vehicleId = 2
                        },
                        new
                        {
                            Id = 3,
                            AvailableSeats = 30,
                            FromStationId = 2,
                            NumberOfSeats = 30,
                            Price = 300,
                            TOStationId = 4,
                            TripDate = new DateTime(2025, 3, 16, 14, 45, 0, 0, DateTimeKind.Unspecified),
                            vehicleId = 3
                        },
                        new
                        {
                            Id = 4,
                            AvailableSeats = 20,
                            FromStationId = 5,
                            NumberOfSeats = 20,
                            Price = 300,
                            TOStationId = 1,
                            TripDate = new DateTime(2025, 3, 17, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            vehicleId = 4
                        });
                });

            modelBuilder.Entity("Transport_system_prototype.Models.vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AirConditioning")
                        .HasColumnType("bit");

                    b.Property<bool>("Drinks")
                        .HasColumnType("bit");

                    b.Property<string>("ImgURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfSeats")
                        .HasColumnType("int");

                    b.Property<bool>("Snacks")
                        .HasColumnType("bit");

                    b.Property<bool>("TV")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("WiFi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AirConditioning = true,
                            Drinks = true,
                            ImgURL = "~/uploads/bus1.jpeg",
                            Name = "Luxury",
                            NumberOfSeats = 150,
                            Snacks = true,
                            TV = true,
                            Type = "Train",
                            WiFi = true
                        },
                        new
                        {
                            Id = 2,
                            AirConditioning = true,
                            Drinks = false,
                            ImgURL = "~/uploads/bus2.jpeg",
                            Name = "Standard",
                            NumberOfSeats = 200,
                            Snacks = false,
                            TV = false,
                            Type = "Train",
                            WiFi = false
                        },
                        new
                        {
                            Id = 3,
                            AirConditioning = true,
                            Drinks = true,
                            ImgURL = "~/uploads/bus3.jpeg",
                            Name = "Comfort",
                            NumberOfSeats = 30,
                            Snacks = true,
                            TV = true,
                            Type = "Bus",
                            WiFi = false
                        },
                        new
                        {
                            Id = 4,
                            AirConditioning = true,
                            Drinks = true,
                            ImgURL = "~/uploads/bus4.jpeg",
                            Name = "Premium",
                            NumberOfSeats = 55,
                            Snacks = false,
                            TV = true,
                            Type = "Bus",
                            WiFi = true
                        });
                });

            modelBuilder.Entity("Transport_system_prototype.Models.Trip", b =>
                {
                    b.HasOne("Transport_system_prototype.Models.Station", "FromStation")
                        .WithMany()
                        .HasForeignKey("FromStationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Transport_system_prototype.Models.Station", "TOStation")
                        .WithMany()
                        .HasForeignKey("TOStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Transport_system_prototype.Models.vehicle", "vehicle")
                        .WithMany()
                        .HasForeignKey("vehicleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FromStation");

                    b.Navigation("TOStation");

                    b.Navigation("vehicle");
                });
#pragma warning restore 612, 618
        }
    }
}
